volumes:
  pnpm-cache:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run dev --host --port 3000
    environment:
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - AIRTABLE_API_BASE=${AIRTABLE_API_BASE}
    working_dir: /app
    volumes:
      - ./:/app
      - pnpm-cache:/root/.pnpm-store
    ports:
      - '3000:3000'
